### ISSUE TITLE
check 89 - short dump

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#1007]
![image](https://user-images.githubusercontent.com/5888506/109531369-18963380-7ab8-11eb-94f1-e632fd81d5c2.png)

![image](https://user-images.githubusercontent.com/5888506/109531436-28ae1300-7ab8-11eb-9e11-1b675ea0a9d3.png)

**Comment by MiLiCLN** [comment]
Version 7.50 and later have a different interface.
![Interface_LXE_OBJ_DOKU_GET_XSTRING_755](https://user-images.githubusercontent.com/49416412/109947574-c0d71280-7cd9-11eb-8644-fb43c0516c54.png)

**Comment by larshp** [comment]
we need to add a try catch thing

**Comment by g-back** [comment]
The version is never filled anyway in AOC and it's an optional parameter below 750. 
Just remove the version as an input parameter in the Z-FM and leave it empty in the actual function call?

**Comment by larshp** [comment]
yea 👍 sounds good

**Comment by g-back** [comment]
OK, you can assign it to me then
