### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by abap-weasel** [larshp/abapOpenChecks#1013]
Hey guys, 

I am an active user of this project and it was quite astonishing how fast checks were implemented when it was started.

Unfortunately there were no new checks since 6+ months and it look like there are currently only housekeeping tasks and bugfixing performed.

Was abapOpenChecks discontinued?

**Comment by larshp** [comment]
still running, pull requests welcome 😄 

But also check out https://abaplint.org, it knows more about the language, which is difficult to implement in ABAP, plus runs on CI.

**Comment by larshp** [comment]
note: 
* the last commit before this issue was opened is 5 hours before, https://github.com/larshp/abapOpenChecks/commit/6b5d936db0e2227f4842453f445c27bf61d5c04f
* the issue previous to this issue was answered within ~12 hours, #1009

**Comment by larshp** [comment]
closing
