### ISSUE TITLE
ZAOC_NAMING & other structures not getting generated 

### ISSUE THREAD

**Issue by nil2087** [larshp/abapOpenChecks#1016]
![image](https://user-images.githubusercontent.com/33514785/113822270-d76dff00-979a-11eb-8754-d5aa6f34b662.png)
![image](https://user-images.githubusercontent.com/33514785/113822282-dd63e000-979a-11eb-9407-6f5655aeec74.png)

Getting these  errors while importing the zip files.
Can you please help check  with these issue ? 

![image](https://user-images.githubusercontent.com/33514785/113822667-58c59180-979b-11eb-92fc-3411ad869412.png)

**Comment by larshp** [comment]
are you running the latest version of abapGit?

**Comment by nil2087** [comment]
ZABAPGIT_full report which existed in my system

**Comment by larshp** [comment]
what is the version number in your system?
![image](https://user-images.githubusercontent.com/5888506/113826257-3bd09480-9782-11eb-9f7f-bfcaddc22c62.png)

**Comment by nil2087** [comment]
![image](https://user-images.githubusercontent.com/33514785/113970723-fa5ce980-9854-11eb-9891-f79c715e8bda.png)
1.94.0

**Comment by larshp** [comment]
update to the latest abapGit and try again

**Comment by nil2087** [comment]
thanks it worked with the suggested fix.

**Comment by larshp** [comment]
closing
