### ISSUE TITLE
CHECK_45: corresponding #( ) adjust message

### ISSUE THREAD

**Issue by g-back** [larshp/abapOpenChecks#1019]
The check suggests to use CORRESPONDING #( ) instead of MOVE-CORRESPONDING - suggestion: adjust the check message to incorporate the "base", because
```abap
move-corresponding source to target.
" this is NOT analogous:
target = corresponding #( source ).
" but this is:
target = corresponding #( base ( target ) source ).
```

The check documentation mentions that `target` is initialized, but changing the check message to `Use corresponding #( base( source ) target )` should make this clearer on first glance.

Thoughts?

**Comment by MiLiCLN** [comment]
We should also mention that "BASE" is only available from 7.40 SP08.

**Comment by larshp** [comment]
if the version is 740sp08 or above issue
"Use corresponding #( base( source ) target )" 
for lower
"Use corresponding #( source ) if source is initial" 

🤷‍♂️

**Comment by g-back** [comment]
Ah, I assumed that `base` was already included when `corresponding` was released. Sounds good, will change it accordingly

**Comment by g-back** [comment]
Heh, it's been a while. I think I stopped following up on this because I couldn't find a method to check the current systems version. Do we have any other checks that have abap version dependent stuff?

**Comment by larshp** [comment]
see
https://github.com/larshp/abapOpenChecks/blob/6b5d936db0e2227f4842453f445c27bf61d5c04f/src/checks/zcl_aoc_check_48.clas.abap#L162 
and
https://github.com/larshp/abapOpenChecks/blob/6b5d936db0e2227f4842453f445c27bf61d5c04f/src/checks/zcl_aoc_check_45.clas.locals_imp.abap#L47

**Comment by MiLiCLN** [comment]
Could you also adapt the documentation in this context?
