### ISSUE TITLE
Discussion: Release Dependent Branches

### ISSUE THREAD

**Issue by MiLiCLN** [larshp/abapOpenChecks#1026]
What do you think? Do we need release dependent branches in the future?
Currently we have the situation that we make adjustments for old systems (#1024 ) but at the same time we have errors / side effects with new releases (#1021).

**Comment by larshp** [comment]
I think avoid branching and forking at all costs, its a loose loose. Maintenance wise there can be one branch much ahead, and one left behind, making it difficult to contribute.

That being said, its also difficult to maintain one branch. The main problem that testing against different ABAP versions is difficult.

**Comment by larshp** [comment]
and again, its really difficult, also because SAP keeps changing stuff(which they should, but they should also make it easy to keep things working)
