### ISSUE TITLE
Error when installing AOC on fresh s/4 2020

### ISSUE THREAD

**Issue by dquercus** [larshp/abapOpenChecks#1029]
Hi,

I'm trying to install the AOC on a fresh just installed S/4 version 2020 and it fails due to following error:

![image](https://user-images.githubusercontent.com/243210/124792735-91693880-df4d-11eb-9cb8-a5d443551f4a.png)

I had to manually force the creation of ZAOC_SEOCLSNAME_RANGE and then ignore the error.

KR

**Comment by larshp** [comment]
are you using the latest abapGit version?

**Comment by dquercus** [comment]
> are you using the latest abapGit version?

I was about to update the ticket :). I was using an old version I copied from an old landscape. With latest version if works without any issue!

Thanks!
