### ISSUE TITLE
Unit tests of several checks fail

### ISSUE THREAD

**Issue by D072189** [larshp/abapOpenChecks#1031]
I installed an up-to-date version of the current main branch and ran the unit tests for all checks. The unit tests of checks 01, 02, 03, 04, 07, 08, 10, 11, 14, 15, 18, 21, 25, 53, 54, 100 all fail for various reasons (some with ABAPUnit assertion failures, some with short dumps, the latter mostly related to the checksum computation not working for the way the checks are executed in the unit tests).

Is there some additional undocumented steps to running the unit tests for these checks properly or are they really all broken?

**Comment by larshp** [comment]
argh, yea, seems broken 😞

**Comment by larshp** [comment]
soo,

001: was broken in https://github.com/larshp/abapOpenChecks/pull/1022

**Comment by larshp** [comment]
@D072189 thanks, can you try the fixes listed above?

**Comment by larshp** [comment]
does https://github.com/larshp/abapOpenChecks/pull/1035 also fix the unit test for check 25?

**Comment by D072189** [comment]
No, that's a different issue but I cannot reproduce it in a vanilla 7.55 box - it's an issue with my DEV system content. I'd say we can close this 👍
