### ISSUE TITLE
Performance Finding -> Select with COUNT(*) on TADIR 

### ISSUE THREAD

**Issue by abap-weasel** [larshp/abapOpenChecks#1036]
This is coming up in TOP List for SQL runtime in our dev system from our weekly scans.

https://github.com/larshp/abapOpenChecks/blob/03b3ddd245b44e2409540057ca92dd036ec7b726/src/checks/zcl_aoc_super.clas.abap#L658-L663

As TADIR is buffered in DDIC, Select Count should be changed.
Care: Possible Values for Genflag in TADIR are ' ', 'X' and 'T' (S4HANA 2020)

**Comment by larshp** [comment]
thanks

I'm not sure what kind of scan or list it is you you have

but suggest changing the code to just get the GENFLAG field, then it should lookup in local buffer?

will you be opening a PR for this?

**Comment by larshp** [comment]
@abap-weasel try #1037

**Comment by abap-weasel** [comment]
yep 👍

fyi: method found via SQLMD transaction. 

![image](https://user-images.githubusercontent.com/47646214/128342354-bfeb8f2d-acd7-42bd-8e9f-7ea2cca77549.png)

**Comment by larshp** [comment]
@abap-weasel if you think its good to merge, please add a comment in the PR, https://github.com/larshp/abapOpenChecks/pull/1037
