### ISSUE TITLE
Import error via abapGit

### ISSUE THREAD

**Issue by preinboth** [larshp/abapOpenChecks#1038]
Clean import, no update.

![image](https://user-images.githubusercontent.com/6295832/129503050-c83a3bb2-7c0f-4b9b-bccc-cc810cd68581.png)

**Comment by larshp** [comment]
are you using the latest abapGit?

**Comment by preinboth** [comment]
GC_XML_VERSION	'v1.0.0'
GC_ABAP_VERSION	'1.105.0'

**Comment by larshp** [comment]
please update to latest version

see https://github.com/abapGit/abapGit/blob/main/changelog.txt#L40

**Comment by preinboth** [comment]
Ok. I thought the version from the SAP Docker Container was current.  Thanks

**Comment by larshp** [comment]
I don't think SAP does updates to the image

but abapGit keeps updating, https://github.com/abapGit/abapGit/commits/main

**Comment by preinboth** [comment]
Everything ok. abapGit updated and repository new pull.  Thanks for the advice.

**Comment by larshp** [comment]
ref #1029

**Comment by MiLiCLN** [comment]
Maybe we should adjust the README.
![aoc_abapgit_installation](https://user-images.githubusercontent.com/49416412/129536698-e03de834-72c4-4e51-af21-d0dc5748914d.png)
