### ISSUE TITLE
Maybe we should adjust the README.

### ISSUE THREAD

**Issue by MiLiCLN** [larshp/abapOpenChecks#1040]
Maybe we should adjust the README.
![aoc_abapgit_installation](https://user-images.githubusercontent.com/49416412/129536698-e03de834-72c4-4e51-af21-d0dc5748914d.png)

_Originally posted by @MiLiCLN in https://github.com/larshp/abapOpenChecks/issues/1038#issuecomment-899335150_

**Comment by larshp** [comment]
feel free to open a PR for it 👍
