### ISSUE TITLE
AOC_SUPER: Check for generated object does not handle ODATA artifacts

### ISSUE THREAD

**Issue by abap-weasel** [larshp/abapOpenChecks#1042]
Generated classes for OData artificats which are generated via SEGW transaction are not covered by check for generated objects:

https://github.com/larshp/abapOpenChecks/blob/32842b2b507061bdb7b693f8489c2c4cc1ee3cc3/src/checks/zcl_aoc_super.clas.abap#L656-L669

TADIR-GENFLAG is not set for them.

It looks like a check for this is implemented in CodePal:
https://github.com/SAP/code-pal-for-abap/blob/65c008f75d4d2453c6994c57dc03741862c1d510/src/foundation/y_exemption_of_class.clas.abap#L151-L158

Can we add the same check in AOC? (If yes: I am not sure about open source approach for that...  Would we just copy this from CodePal or how is the proper way to handle that? 😬)

**Comment by larshp** [comment]
I think it's okay to use a similar SELECT statement, note it won't be the same since the naming of variables is different

**Comment by larshp** [comment]
also note the code in https://github.com/larshp/abapOpenChecks/blob/5a382160dc588bd9fd511f023aaf58a3451cd97d/src/checks/zcl_aoc_super.clas.abap#L188

**Comment by abap-weasel** [comment]
my fault, someone else changed our default check variant to inlude extended checks from standard instead AOC and I thought unwanted findings are coming from AOC. Existing check works as expected and no error in AOC. => Closed.
