### ISSUE TITLE
dump "ASSERTION_FAILED" in ZCL_AOC_PARSER->XML_GET because of table SSYNTAXSTRUCTURE 

### ISSUE THREAD

**Issue by TestiTestmann91** [larshp/abapOpenChecks#1043]
Hi,

ASSERT sy-subrc = 0 fails because internal table gt_syntax is not filled via select statement above.
![grafik](https://user-images.githubusercontent.com/91332263/134691965-f367a75c-ca5c-4df6-a558-2e5f02f12d65.png)

DB table SSYNTAXSTRUCTURE field proglang is not filled.
![grafik](https://user-images.githubusercontent.com/91332263/134692141-a9fa1335-af76-43d0-a76b-f1893945913f.png)

Is this a problem with the system settings or some "real" issue from AOC?
Thanks!

**Comment by larshp** [comment]
hmm, heh, I'd assume the field to be filled

however, try replacing the where condition, to "prolang = 'A' or prolang = '' or prolang is null" it should be a safe change, pull request welcome 😄

**Comment by TestiTestmann91** [comment]
Currently we're using the standalone version of abapGIT plus I'm fairly new to the subject as a whole. But I will take a look into upgrading to developer version next week as trying to submit changes runs into a authorization problem :( 
![grafik](https://user-images.githubusercontent.com/91332263/134705736-be356d32-63ed-4d67-be6a-cf9978af34ef.png)
And I checked my credentials more than enough 😆 

As for now I can confirm that the (local) change solves my problem.

**Comment by larshp** [comment]
you can always use the web editor to change the code, https://github.com/larshp/abapOpenChecks/edit/main/src/parsing/zcl_aoc_parser.clas.abap or https://blogs.sap.com/2021/09/03/editing-abap-code-directly-on-github/
