### ISSUE TITLE
ATC Check 69: Conversion Exits are being scanned - when they should be ignored

### ISSUE THREAD

**Issue by cavabap** [larshp/abapOpenChecks#1046]
There is small bug here adt://***/sap/bc/adt/oo/classes/zcl_aoc_check_69/source/main#start=1432,4;end=1435,51 in zcl_aoc_check_69
    
`IF ms_naming-set_cfunc = abap_true
        AND rv_skip = abap_false
        AND ( iv_name CS 'CONVERSION_EXIT_*_INPUT'
        OR iv_name CS 'CONVERSION_EXIT_*_OUTPUT' ).`

But it should be 
`IF ms_naming-set_cfunc = abap_true
        AND rv_skip = abap_false
        AND ( iv_name CP 'CONVERSION_EXIT_*_INPUT'
        OR iv_name CP 'CONVERSION_EXIT_*_OUTPUT' ).`
Additionaly one could consider checking that the * is at least one letter (or does it need to be 5?). But then I guess we're moving to REGEX's.

Can the project handle the correction or should I submit a PR?

**Comment by larshp** [comment]
feel free to submit a pull request 😃

**Comment by cavabap** [comment]
Ugh... i was hoping not to :) nevermind, PR is on the way.

The class doesn't seem to have a lot of unit tests. And it looks like I'd need to know quite a bit about zcl_aoc_scan to unit test anything.
