### ISSUE TITLE
IF in IF - False Positive

### ISSUE THREAD

**Issue by hardyp** [larshp/abapOpenChecks#1049]
The following code:-
![image](https://user-images.githubusercontent.com/7078215/136636324-dee2a90f-0068-4a4e-a030-416b60943568.png)

Generates the following error:-

![image](https://user-images.githubusercontent.com/7078215/136636337-c687fcdb-aa02-4f84-8bba-c0672cdfcbdb.png)

Unless I am missing something obvious, if the IF/ENDIF block in the middle contains an ELSE statement then the code cannot be reduced, unless you repeat the outer logical expression in the lines in the IF/ELSE/ENDIF construct.

**Comment by Dwivedirahul44** [comment]
I think a small change at Check_01 -> Method contains_else to also look for else-if branch might help.
- Unit test results after adding a new scenario
<img width="693" alt="Untitled (2)" src="https://user-images.githubusercontent.com/43263062/196640730-4c96b69d-b823-4ccb-beb4-63a0fc8a65db.png">

Adding below code:
`      IF lo_structure->get_type( ) = zcl_aoc_scan=>gc_structure_statement-else
      or lo_structure->get_type( ) = zcl_aoc_scan=>gc_structure_statement-elseif
      .`
All test pass post-changes.

<img width="632" alt="Untitled" src="https://user-images.githubusercontent.com/43263062/196638759-03584b4a-3f31-4bb5-93c2-80cc242cada2.png">

Let me know if this works, I will add PR.

**Comment by larshp** [comment]
@Dwivedirahul44 suggest just go ahead and opening the PR, its easier to read the code, plus it can be tested

**Comment by Dwivedirahul44** [comment]
PR added.
