### ISSUE TITLE
Check 079: clear with false positive 

### ISSUE THREAD

**Issue by MartinH1337** [larshp/abapOpenChecks#1060]
DATA ls_struc TYPE /my/struc.
CLEAR ls_struc **WITH** abap_true. 

this leads to a 079 `CLEAR as first use of variable`

**Comment by larshp** [comment]
thanks for the bug report, pull requests welcome

**Comment by MartinH1337** [comment]
#1061

**Comment by larshp** [comment]
fix by @MartinH1337 merged, so closing the issue
