### ISSUE TITLE
Question: not all checks available

### ISSUE THREAD

**Issue by preinboth** [larshp/abapOpenChecks#1069]
Hello, I have imported the package using abapGit. However, not all checks are implemented in the SCI. How can this be cleaned up?

![image](https://user-images.githubusercontent.com/6295832/161487266-eb0a24d2-500e-4977-9689-9cf849a54778.png)

**Comment by larshp** [comment]
argh, yea, thats a mess

I think code inspector keeps a cache of it, make sure there are no dumps in the system, and try making a dummy change in each check class

**Comment by preinboth** [comment]
So, I have now changed some check classes (changed blank lines) and activated them. Even a complete system restart did not bring a positive result. However, I am only a user in this area.  I have the same problem with abapLint.
Note: I use the ABAP Developer version in the Docker container. Are there any other ideas?

**Comment by larshp** [comment]
did the dummy change and activate work?

**Comment by preinboth** [comment]
no, unfortunately not.

**Comment by preinboth** [comment]
For posterity:

In "Code Inspector -> Management of -> Checks" the missing checks were not selected.
