### ISSUE TITLE
CHECK_79: Not RFC enabled, but described as RFC enabled in Docs

### ISSUE THREAD

**Issue by BlackmanCC** [larshp/abapOpenChecks#1087]
I installed the newest release version and CHECK_79 is not RFC enabled:
![image](https://user-images.githubusercontent.com/56150286/192523125-8edf5094-3e84-4580-9f85-421ab343a385.png)

In docs it is shown as RFC enabled:
https://docs.abapopenchecks.org/checks/79/
![image](https://user-images.githubusercontent.com/56150286/192523248-00a0824b-369a-4ab5-8fcc-f82c7f646225.png)

Is this a mistake in docs or is check not RFC enabled?

**Comment by larshp** [comment]
not RFC enabled, it uses `zcl_aoc_compiler`

**Comment by larshp** [comment]
updated with https://github.com/larshp/abapOpenChecks/pull/1088
