### ISSUE TITLE
Error: Pretty printer settings do not match

### ISSUE THREAD

**Issue by jelliottp** [larshp/abapOpenChecks#1104]
I'm running into a situation where we receive `Pretty printer settings do not match` error when running the checks during our CI process to release the transport. However, I do not get this error when running the checks in the GUI or Eclipse. 

Any idea? What exactly is this error meant to indicate?

**Comment by larshp** [comment]
the intention is to check if the user pretty print settings match the settings in code inspector

which user runs the CI process? what is the pretty print settings for that user?

**Comment by jelliottp** [comment]
Thanks for that hint, we're looking into this now.

**Comment by jelliottp** [comment]
We were able to track down the settings for the user executing the checks in CI, and then force update the settings.

**Comment by jelliottp** [comment]
Re-opening, created https://github.com/larshp/abapOpenChecks/pull/1107
