### ISSUE TITLE
CHECK_83: Reference of DDIC object not found in function module signature

### ISSUE THREAD

**Issue by ConjuringCoffee** [larshp/abapOpenChecks#1115]
Hi all, I'm getting the message "Unreferenced DDIC object" for a data element that is only used in the signature of a function module.

Here's a minimal example I set up:

![image](https://github.com/larshp/abapOpenChecks/assets/72548231/fd88715a-31a3-4b3e-a3f2-8b23d2790d4e)

![image](https://github.com/larshp/abapOpenChecks/assets/72548231/e94a102d-8049-4f3d-81dc-f6b9a53ca9ca)

The standard where-used list is able to find the reference:

![image](https://github.com/larshp/abapOpenChecks/assets/72548231/0fa16dac-dee3-4edb-9aea-07bbe76bc73c)

**Comment by ConjuringCoffee** [comment]
The signature of function modules seems to be stored in table `FUPAREF`:

![image](https://github.com/larshp/abapOpenChecks/assets/72548231/92477bbc-5b3d-44f3-8c3f-e68fd7ac550c)

I could add it to the already existing selections in `ZCL_AOC_CHECK_83` but I'm not sure that's the best approach. Maybe we should use similar logic / data to the standard where-used list instead? (I haven't done any research in that direction yet though.)

**Comment by larshp** [comment]
I think the current approach in ZCL_AOC_CHECK_83 is for speed, easiest/safest would be just add the extra selection
