### ISSUE TITLE
Using `ZCL_AOC_SUPER` vs. `ZCL_AOC_SUPER_ROOT`

### ISSUE THREAD

**Issue by ConjuringCoffee** [larshp/abapOpenChecks#1127]
Does anyone know when to use `ZCL_AOC_SUPER` or when to use `ZCL_AOC_SUPER_ROOT`? It seems like `ZCL_AOC_SUPER_ROOT` is essentially the same as `ZCL_AOC_SUPER`, but with less functionality...? I can't really tell what the intention is for having two super classes for the checks.

**Comment by larshp** [comment]
ZCL_AOC_SUPER: for code based checks, its based on the standard scan super class

ZCL_AOC_SUPER_ROOT: for non code based, or if implementing the code check from scratch

**Comment by ConjuringCoffee** [comment]
Thanks 👍
