### ISSUE TITLE
New Check:  ATC for using selects over the tables with replacement object (like MARC)

### ISSUE THREAD

**Issue by fidley** [larshp/abapOpenChecks#1134]
Hi,
I have a question if any of the AOC is serving the check over the SELECT statement and usage of tables which have now replacement object, for example table MARC has the replacement object NSDN_E_MARC which is causing performance problems. I we use instead a select on V_MARC_MD (DB view), then the performance significantly improves.

So the full question is, do we have such check already?

Cheers
Łukasz

**Comment by larshp** [comment]
I dont think it exists yet

**Comment by fidley** [comment]
Ok. Then I'll try to build one and make a PR if you think it's interesting.

**Comment by larshp** [comment]
its interesting 😄

**Comment by fidley** [comment]
@larshp some questions:

1. have you ever included pseudo comment for AOC? If yes, was there any naming convention? Is it welcomed or from definition you don't want them in AOC?
2. Do you know how to pass more information to details?
![image](https://github.com/larshp/abapOpenChecks/assets/7912195/dcad3cf6-6d9c-43e4-a049-4dff3e91b86e)

**Comment by fidley** [comment]
3. Quickfixes - I guess because of backward compatibility, there is now way to include quickfixes inside without dynamic check of class/instances existence and dynamic calls of the methods?

**Comment by fidley** [comment]
> 3. Quickfixes - I guess because of backward compatibility, there is now way to include quickfixes inside without dynamic check of class/instances existence and dynamic calls of the methods?

Ok this I found in the documentation https://www.sap.com/documents/2018/09/905bfdab-1a7d-0010-87a3-c30de2ffd8ff.html - in the part CREATING DOCUMENTATION.

**Comment by fidley** [comment]
> > 3. Quickfixes - I guess because of backward compatibility, there is now way to include quickfixes inside without dynamic check of class/instances existence and dynamic calls of the methods?
> 
> Ok this I found in the documentation https://www.sap.com/documents/2018/09/905bfdab-1a7d-0010-87a3-c30de2ffd8ff.html - in the part CREATING DOCUMENTATION.
![image](https://github.com/larshp/abapOpenChecks/assets/7912195/963f08f3-3030-4e6f-a1d5-f24ef2f4503b)

**Comment by larshp** [comment]
1: pseudo comments, didnt find any, but they are welcome, perhaps some of the code in [check 78](https://docs.abapopenchecks.org/checks/78/) can be reused
2: no
3: yea, backwards compatibility

**Comment by fidley** [comment]
1. & 2. I have already done and I will commit soon.
3. Almost done with dynamic calls but I have no chance to check on older releases :(

**Comment by larshp** [comment]
merge https://github.com/larshp/abapOpenChecks/pull/1135 first before doing fixes?

**Comment by fidley** [comment]
why not
