### ISSUE TITLE
Check 103: Unit test fails when quickfix method doesn't exist

### ISSUE THREAD

**Issue by ConjuringCoffee** [larshp/abapOpenChecks#1143]
The unit test `DATABASE_SELECT_03` for `ZCL_AOC_CHECK_103` fails with the following error:

> Method call of CREATE_QUICKFIX_ALTERNATIVES failed; the class CL_CI_QUICKFIX_CREATION does not exist

Maybe this ATC check needs to verify if the required methods even exist as a precondition?

I tested this on release 7.50. The class `CL_CI_QUICKFIX_CREATION` doesn't exist on that release at all.

Tagging the check creator: @fidley

**Comment by fidley** [comment]
Will check it.

**Comment by fidley** [comment]
Better validation of the availability of quick fixes needs to be done. The rest of the check should work even without it. I will correct this. Can you share the exemption you get? Or dump ;)

**Comment by ConjuringCoffee** [comment]
`Exception Error <DYN_CALL_METH_CLASS_NOT_FOUND>`

Analysis 
```
'Method call of CREATE_QUICKFIX_ALTERNATIVES failed; the class CL_CI_QUICKFIX_CREATION does not exist' 
Test 'LTCL_TEST->DATABASE_SELECT_03' in Main Program 'ZCL_AOC_CHECK_103=============CP'. 
```

Stack
```
Include: <ZCL_AOC_CHECK_103=============CCIMP> Line: <56> 
Include: <ZCL_AOC_CHECK_103=============CM001> Line: <56> (CHECK) 
Include: <ZCL_AOC_UNIT_TEST=============CM001> Line: <11> (CHECK) 
Include: <ZCL_AOC_CHECK_103=============CCAU> Line: <40> (EXECUTE_CHECK) 
Include: <ZCL_AOC_CHECK_103=============CCAU> Line: <64> (DATABASE_SELECT_03) 
```

**Comment by fidley** [comment]
Simple TRY/CATCH block added. This should resolve issue. If not, please reopen.
