### ISSUE TITLE
check 45, NEW

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#261]
is it possible to use NEW combined with non-class based exceptions?

``` abap
data: lo_source TYPE REF TO cl_oo_source.

    CREATE OBJECT lo_source
      EXPORTING
        clskey             = ls_clskey
      EXCEPTIONS
        class_not_existing = 1
        OTHERS             = 2.
```

**Comment by pcf0** [comment]
I came across the same problem today.
It's not possible to use the new variant with non-class based exceptions.

ABAP documentation: https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenconstructor_expression_new.htm
>  Non-class-based exceptions of the instance constructor cannot be handled, which means that sy-subrc is never set to a value other than 0.

**Comment by larshp** [comment]
suggest adding the following logic:
scan the statement for word "EXCEPTIONS" if the statement contains it, skip reporting NEW error

**Comment by pcf0** [comment]
i will look into it
