### ISSUE TITLE
colon, check 23

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#289]
error should be shown for:

```abap
CATCH: cx_root.
```

https://github.com/larshp/abapOpenChecks/wiki/ZCL_AOC_CHECK_23

**Comment by VishnAndr** [comment]
What's bad in cx_root catching? Nothing found in the link source. Yes, it's better to define catch for particular exception class. However, I personally use cx_root as "catch any" exception in case I know what I'm doing. Just interested in your opinion.

**Comment by larshp** [comment]
nothing wrong with the CX_ROOT catching, it is the chaining/colon that looks suspicious to me.

see http://help.sap.com/abapdocu_740/en/abenchained_statements_guidl.htm,
"Use chained statements mainly for declarations"

Would like
```abap
CATCH: cx_root.
```

to be 
```abap
CATCH cx_root.
```

instead. Code like

```abap
CATCH: cx_root, cx_something.
```

would expand to:

```abap
CATCH cx_root.
CATCH cx_something.
```

which would probably be wrong.

**Comment by VishnAndr** [comment]
Oh, now I see. Got what you mean. Thanks!
