### ISSUE TITLE
feature request: find empty unit test methods

### ISSUE THREAD

**Issue by kaysap** [larshp/abapOpenChecks#366]
I think it would be nice to have a check for empty unit test methods ("FOR TESTING"), as these will always be green.

Since we tend to rely on green lights, there might be a risk that these will not be looked into again...

Best regards and thanks for your work!

**Comment by larshp** [comment]
yeah, it should be quite easy to find.

Sometimes I add a comment and RETURN in a unit test method, would you also regard this as empty? Or only when there are no statements? Methods containing only comments are also to be considered empty?

```abap
METHOD test001.
* Cannot be tested due to blah blah
  RETURN.
ENDMETHOD.
```

**Comment by kaysap** [comment]
My main concern is that empty unit test methods are shown as successful when the tests are run.
Does it make sense to write an empty test method? I prefer to add a 
`cl_abap_unit_assert=>fail( level = if_aunit_constants=>tolerable msg = 'unit test missing' ) `
statement.

**Comment by kaysap** [comment]
... sorry, I just found that this check is already implemented in the SCI standard checks :-o
You can activate this by setting this parameter:
![grafik](https://cloud.githubusercontent.com/assets/11522893/26544388/f038138a-4461-11e7-92b3-2639c645fbf6.png)
