### ISSUE TITLE
DELETE...WHERE instead of LOOP-DELETE...FROM

### ISSUE THREAD

**Issue by VishnAndr** [larshp/abapOpenChecks#406]
Is it possible to implement a check to assess the following?
```
LOOP AT lt_tab ASSIGNING <fs> WHERE ...
   DELETE lt_tab FROM <fs>.
ENDLOOP.
```

It should be replaced with:
`DELETE lt_tab WHERE ...`

Quite a performance issue.

Ref: https://wiki.scn.sap.com/wiki/display/ABAP/How+to+avoid+modify+and+delete+statements+inside+loop+end+loop+using+field+symbols

**Comment by larshp** [comment]
yes, it should be possible, thanks. 

So many ideas so little time 😄

**Comment by larshp** [comment]
@VishnAndr implemented, try `ZCL_AOC_CHECK_62`

**Comment by VishnAndr** [comment]
@larshp you are a legend!! 👍 Thanks! Will try it during the week.

**Comment by larshp** [comment]
the example in the wiki is more complicated than your example, I've implemented exactly your example, see unit tests in:
https://github.com/larshp/abapOpenChecks/blob/master/src/checks/zcl_aoc_check_62.clas.testclasses.abap

**Comment by larshp** [comment]
@VishnAndr did it work out?

**Comment by VishnAndr** [comment]
Yes, it worked perfectly well in my particular case. Thank you Let's leave it as is and see if anything similar comes up in the future.
