### ISSUE TITLE
RFC enabled Code Inspector checks

### ISSUE THREAD

**Issue by se38** [larshp/abapOpenChecks#422]
Hello Lars,
currently I'm implementing a central ATC landscape (central ATC server with 7.51 and satellite DEV systems).
To use Code Inspector checks in such a landscape, the checks have to be RFC-enabled (see https://blogs.sap.com/2017/02/27/remote-code-analysis-in-atc-for-developers/ ).

Do you know already how to RFC-enable the abapOpenChecks? Or should we ask Thomas Fiedler?
If you publish a How-To on the wiki page, I'd help you to RFC-enable the checks one-by-one.

Cheers, Uwe (aka @se38)

**Comment by larshp** [comment]
Hi,
I looked into it a while ago, see https://github.com/larshp/abapOpenChecks/issues/336

Somewhere there is a restriction that only static checks are executed remotely, however I'm not sure what it means, and dont remember much about it.

**Comment by se38** [comment]
Don't have any idea neither. If you look in a 7.51 system (ie the developer edition) you can identify the RFC-enabled check by the flash.
![atc](https://user-images.githubusercontent.com/5384144/30645394-ede1ff2a-9e15-11e7-824b-b362db30da52.PNG)
I asked alred on SCN and will report back, as soon as I get an answer:. https://blogs.sap.com/2017/02/27/remote-code-analysis-in-atc-for-developers/#comment-391832

**Comment by larshp** [comment]
setting `REMOTE_RFC_ENABLED = ABAP_TRUE` in the constructor, and the icon shows up. However I get a strange dump in CL_ABAP_COMP_PROCS_E, but I'm also trying to setup central checks using just 1 system

![image](https://user-images.githubusercontent.com/5888506/30657496-13a81bbe-9e38-11e7-90e8-bf23a33665f0.png)

![image](https://user-images.githubusercontent.com/5888506/30657477-04252e02-9e38-11e7-8634-1f6e8d4b1edc.png)

**Comment by larshp** [comment]
try this: https://github.com/larshp/abapOpenChecks/pull/423

**Comment by se38** [comment]
Ha, you made it (again). This fix works. Here's the (RFC!) result for Check #11 :
![atc](https://user-images.githubusercontent.com/5384144/30682812-46d34a18-9eab-11e7-9015-495e5231ce46.PNG)

Just one Q:
What's the reason you want to ASSIGN the variable in the constructor? "remote_rfc_enabled  = abap_true." simply works also.

**Comment by larshp** [comment]
I have merged the branch.

ASSIGN: I assume the field does not exist in versoin 702, abapOpenChecks is targeted 702 and higher.

Feel free to open a PR with additional fixes, note that some of the checks uses more than just the code scan information. Also I would like to move the code for setting RFC enabled to a method in ZCL_AOC_SUPER

```abap
ASSIGN ('REMOTE_RFC_ENABLED') TO <lv_rfc>.
IF sy-subrc = 0.
  <lv_rfc> = abap_true.
ENDIF.
```

**Comment by larshp** [comment]
Hi,
I have enabled more checks now, these are the ones I think will work via RFC, but I have not tested them

**Comment by se38** [comment]
I've checked some of the new RFC-enabled checks -> perfect, gracias

**Comment by larshp** [comment]
now also shown in the documentation, http://docs.abapopenchecks.org/checks/
