### ISSUE TITLE
Check: 61 - BREAK-POINT

### ISSUE THREAD

**Issue by foessleitnerj** [larshp/abapOpenChecks#458]
Hi,

looks like the CHECK 61 is not ready yet. Anyway, in the CHECK method, a BREAK POINT is inside.

lg Föß
![image](https://user-images.githubusercontent.com/28662231/33348369-796fb968-d496-11e7-8fad-5d6c8e49bd27.png)

**Comment by larshp** [comment]
true, see https://github.com/larshp/abapOpenChecks/wiki, check 61 is work in progress

**Comment by foessleitnerj** [comment]
sorry, of course you are absolutely right!

Thx

**Comment by larshp** [comment]
Ideally I should have kept the code in a branch, but I'm too lazy 😉
