### ISSUE TITLE
Type "SVER_R_DEVCLASS" is unknown in ZCL_AOC_CHECK_32

### ISSUE THREAD

**Issue by hhelibeb** [larshp/abapOpenChecks#467]
Hi Lars,
I worked on the checks of code inspector for several days until I found abapOpenChecks
. It is great! Then I determined to install it.
But when activating  ZCL_AOC_CHECK_32, the syntax check hints an error "Type 'SVER_R_DEVCLASS' is unknown". Can I use any other type as substitution?
My system version is S/4 1709.

**Comment by larshp** [comment]
Do you have any of the following? Preferably PACKRANGE, SE16S_DEV_T or  TYP_R_PACKAGE? Alternatively just delete class ZCL_AOC_CHECK_32, the checks are independent, so everything will work without check 32.

CVT_SODEV
ECSTAT_T_RANGE_PACKET
ETRANGE_PACKAGE_TT
IAC_RANGE_PACKAGE
LXE_TT_DC
LXE_TT_PACKG
PACKRANGE
RLB_R_DEVC
RSO_TR_DEVCLASS
SE16S_DEV_T
SQLMDEVCLASSESRANGE
SQLM_API_PACKAGE_RANGE
SVER_PACKAGES
SVER_R_DEVCLASS
TYP_R_PACKAGE
TYP_R_PACKAGERNG

**Comment by larshp** [comment]
Cool, I will update the code sometime later, please keep the issue open until the code is updated
