### ISSUE TITLE
Checking if the exception is resumable

### ISSUE THREAD

**Issue by pacheco7** [larshp/abapOpenChecks#496]
If the source has the following code will do?

```abap
TRY .
    DATA(x) = NEW string( w_j_1bnfdoc-brgew ).
    
    " This statement raise exception
    value_old_imp = CONV mgvgw( x->*(6) ).
  CATCH BEFORE UNWIND cx_sy_conversion_overflow INTO DATA(err_conversion_overflow).
     " This will raise dump too 
    RESUME.
ENDTRY.
```

The correctly way is:

```abap
TRY .
    DATA(x) = NEW string( w_j_1bnfdoc-brgew ).

    value_old_imp = CONV mgvgw( x->*(6) ).
  CATCH BEFORE UNWIND cx_sy_conversion_overflow INTO DATA(err_conversion_overflow).
    IF err_conversion_overflow->is_resumable = abap_true.
      RESUME.
    ENDIF.
ENDTRY.
```

**Comment by larshp** [comment]
so there must be a check on is_resumeable, `IF err_conversion_overflow->is_resumable = abap_true.` before RESUME?

**Comment by pacheco7** [comment]
Yes, for this case, if the statement CATCH BEFORE UNWIND is writed and inside of this block is a RESUME statement, the system will raise dump and show on the error what is necessary to check if this exception class is resumable.
