### ISSUE TITLE
extended naming standard, custom implementation

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#507]
exclude:
* constructor parameters in exception classes
* conversion exit function module parameter names
* idoc processing function module parameter names
* bw extractors, function module parameter names
etc

[:nspace:]
[:type:]

+ show expected naming in error msg

**Comment by larshp** [comment]
branch https://github.com/larshp/abapOpenChecks/tree/naming

**Comment by larshp** [comment]
split into more message ids

**Comment by larshp** [comment]
merged to master, ready for testing

**Comment by larshp** [comment]
thanks, try again, latest version

**Comment by pcf0** [comment]
yep, it is fixed 👍

**Comment by larshp** [comment]
oh, this is done, closing
