### ISSUE TITLE
Remove redundancies in check constructors

### ISSUE THREAD

**Issue by pcf0** [larshp/abapOpenChecks#518]
In every check constructor you set the `description` and `category`.

I suggest to use a constructor in superclass `ZCL_AOC_SUPER` to set the category to `'ZCL_AOC_CATEGORY'` because it never changes.

I would also go so far and get the class description and set it to `description`. It removes a hard coded string. IMHO it should not be different.
The class description is language-dependent stored in the table `vseoclass`.

ref https://github.com/larshp/abapOpenChecks/pull/514#issuecomment-388331148

**Comment by larshp** [comment]
okay, if implementing this, then all the existing check constructors should also be changed

note that there is currently 2 different super classes, see https://github.com/larshp/abapOpenChecks/issues/240
