### ISSUE TITLE
70: syntax errors

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#519]
fixed some syntax errors in check 70, `char20_t` did not exist in NWABAP751 trial

still some errors left to fix

**Comment by larshp** [comment]
@pcf0 suggest defining the char20_t as custom z object in ddic

**Comment by pcf0** [comment]
Or using `SCI_T_REGULAR_EXPRESSIONS` which is also used in check 39?

**Comment by larshp** [comment]
yeah, better
