### ISSUE TITLE
CORRESPONDING - CHECK_45 - Use expressions

### ISSUE THREAD

**Issue by se38** [larshp/abapOpenChecks#526]
For the CHECK_45 "Use expressions" I'd suggest to implement also the check for MOVE-CORRESPONDING. It should be replaced by the [CORRESPONDING operator](https://help.sap.com/doc/abapdocu_740_index_htm/7.40/en-US/index.htm?file=abenconstructor_expr_corresponding.htm)

**Comment by se38** [comment]
@larshp : how do you want to get the changes? (I don't have direct access via abapGit / Git because of Certificate interception by our firewall). Via Branch/Pull request here on the website? (I'm currently not a contributor). Or via Google drive? Or...

**Comment by larshp** [comment]
via pull request here

suggest either edit the file via the web interface, or export the package to zip and use a normal git client outside of the company network.

**Comment by larshp** [comment]
cool, thanks, can you also help adding it in the documentation, https://github.com/larshp/abapOpenChecks/blob/master/docs/_checks/45.md

http://docs.abapopenchecks.org/checks/45/

**Comment by se38** [comment]
Did the needful (pull request 530)
