### ISSUE TITLE
http 407 error...

### ISSUE THREAD

**Issue by ffischer1984** [larshp/abapOpenChecks#538]
seems a little bit like there is no ssl installed at the sap-server. would be nice if it is validated before the user tries to clone a project ;)

**Comment by larshp** [comment]
In abapGit,
The installation, https://docs.abapgit.org/guide-install.html
and SSL setup, https://docs.abapgit.org/guide-ssl-setup.html
contains a step to validate the SSL setup, https://docs.abapgit.org/other-test-ssl.html

**Comment by larshp** [comment]
@ffischer1984 any luck?

**Comment by ffischer1984** [comment]
hi larshp,
sorry for my late response. I hadn't no look.
Here is a screenshot from my imported certificates: [here](https://www.dropbox.com/s/rcudx8mh1h5q0r3/strust.PNG?dl=0)

Here is the log from abapgit_test_ssl:
06.06.2018                                                                                                                    ssl test für git                                                                                                                           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Error Number     1

SSL handshake with github.com:443 failed: SSSLERR_SSL_READ (-58)
SAPCRYPTO:SSL_read() failed
SapSSLSessionStartNB()==SSSLERR_SSL_READ
  SSL:SSL_read() failed  (536875120/0x20001070)
  => "received a fatal TLS1.0 protocol version alert message from the peer"
  SSL:SSL_get_state()==0x2120 "TLS read server hello A"
  SSL NI-hdl 152: local=172.27.119.31:48270  peer=192.30.253.112:443
  cli SSL session PSE "/usr/sap/N01/DVEBMGS00/sec/SAPSSLA.pse"
  Target Hostname="github.com"
>> ---- SecuSSL ErrStack: ----
0x20001070 | SAPCRYPTOLIB | SSL_read
SSL API error
received a fatal TLS1.0 protocol version alert message from the peer
0xa0600278 | SSL | ssl3_read_bytes
received a fatal TLS1.0 protocol version alert message from the peer
0xa0600278 | SSL | ssl3_connect
received a fatal TLS1.0 protocol version alert message from the peer
0xa0600278 | SSL | ssl3_read_bytes
received a fatal TLS1.0 protocol version alert message from the peer
<< ---------------------------
Also check transaction SMICM -> Goto -> Trace File -> Display End

----

Error Number     1

SSL handshake with api.github.com:443 failed: SSSLERR_SSL_READ (-58)
SAPCRYPTO:SSL_read() failed
SapSSLSessionStartNB()==SSSLERR_SSL_READ
  SSL:SSL_read() failed  (536875120/0x20001070)
  => "received a fatal TLS1.0 protocol version alert message from the peer"
  SSL:SSL_get_state()==0x2120 "TLS read server hello A"
  SSL NI-hdl 153: local=172.27.119.31:52127  peer=192.30.253.116:443
  cli SSL session PSE "/usr/sap/N01/DVEBMGS00/sec/SAPSSLA.pse"
  Target Hostname="api.github.com"
>> ---- SecuSSL ErrStack: ----
0x20001070 | SAPCRYPTOLIB | SSL_read
SSL API error
received a fatal TLS1.0 protocol version alert message from the peer
0xa0600278 | SSL | ssl3_read_bytes
received a fatal TLS1.0 protocol version alert message from the peer
0xa0600278 | SSL | ssl3_connect
received a fatal TLS1.0 protocol version alert message from the peer
0xa0600278 | SSL | ssl3_read_bytes
received a fatal TLS1.0 protocol version alert message from the peer
<< ---------------------------
Also check transaction SMICM -> Goto -> Trace File -> Display End

**Comment by larshp** [comment]
See:
https://docs.abapgit.org/guide-ssl-setup.html
and
https://github.com/larshp/abapGit/issues/1225

"
On Feburary 22nd, GitHub deprectated weak TSL connections.

See SAP note 510007, section 7, for information on how to configure SSL.

Add profile parameters:

ssl/client_ciphersuites = 150:PFS:HIGH::EC_P256:EC_HIGH
ssl/ciphersuites = 135:PFS:HIGH::EC_P256:EC_HIGH
"

**Comment by larshp** [comment]
@ffischer1984 did https://github.com/larshp/abapGit/issues/1491 also solve the above issue?

**Comment by larshp** [comment]
closing, no reply
