### ISSUE TITLE
CHECK_69 - Naming Conventions: Allow prefix ltd for local test double class?

### ISSUE THREAD

**Issue by JohannesKonings** [larshp/abapOpenChecks#562]
Bad naming for a local test double class. Should ltd be allowed?

![image](https://user-images.githubusercontent.com/14806640/42593666-676a18a4-854d-11e8-91ff-d04c3061da3e.png)

**Comment by larshp** [comment]
Hi, I havent really figured out the categorization of test classe, in above example it is a test double, but is also a mock class? Most important to me is being able to tell in SE80 if the class is for testing or contains application logic

**Comment by JohannesKonings** [comment]
You're right

**Comment by larshp** [comment]
these are just the default settings, users can modify this as needed
