### ISSUE TITLE
Error installation AOC deserialize

### ISSUE THREAD

**Issue by hervianzhou** [larshp/abapOpenChecks#565]
Hi Lars,

I have a problem when deserialize AOC, please kindly help me to solve this issue.
SAP_BASIS	752
SAP_ABA	75C

Missing RAISING clause in interface
    Program                                 ZCL_ABAPGIT_OBJECT_CHAR=======CP
    Include                                 ZCL_ABAPGIT_OBJECT_CHAR=======CM005

 Exception 'CX_CLS_INVALID_ATTR_DATA' is always raised when i try to install via zip. i cannot install using close online project because some of limitation. 

please kindly 

Thanks,

**Comment by larshp** [comment]
issue reproduced, workaround is downloading abapOpenChecks as zip and removing the CHAR and AVAS files

**Comment by larshp** [comment]
@hervianzhou try again, use latest abapGit version

**Comment by hervianzhou** [comment]
@larshp wow.. it's worked like a charm.. sorry for late response..
