### ISSUE TITLE
Check 12 - Specify SORT order - order before BY

### ISSUE THREAD

**Issue by pcf0** [larshp/abapOpenChecks#644]
You can specify `ASCENDING` or `DESCENDING` before `BY`.
e.g.
```abap
sort lt_table ascending by comp1 comp2 comp3.
```

This is ignored by check 12. Is that on purpose?
https://github.com/larshp/abapOpenChecks/blob/20f1933a56be23a456b68dc65e35025abfc7f085/src/checks/zcl_aoc_check_12.clas.abap#L50

refrence:
- https://help.sap.com/doc/abapdocu_752_index_htm/7.52/de-DE/abapsort_itab.htm
- [7.02 Wayback Machine](https://web.archive.org/web/20161201141816/http://help.sap.com:80/abapdocu_702/en/abapsort_itab.htm)

**Comment by larshp** [comment]
no, its a bug in abapOpenChecks 😄
