### ISSUE TITLE
"Use new operator" for components named like ABAP tokens

### ISSUE THREAD

**Issue by flaiker** [larshp/abapOpenChecks#658]
![image](https://user-images.githubusercontent.com/5270359/52340673-abb32b00-2a10-11e9-814e-c8941fdbf2db.png)

![image](https://user-images.githubusercontent.com/5270359/52340682-b40b6600-2a10-11e9-8dda-3253244372f8.png)

Seems like component names of a data structure are interpreted as tokens in a check. But the error message does not make much sense either.

**Comment by flaiker** [comment]
Fixing this might be quite a bit of effort, in my case I can exempt the finding and it's unlikely there will ever be another one.

**Comment by larshp** [comment]
yeah, we have too little information about the ABAP language in abapOpenChecks

suggest implementing workaround in abapOpenChecks, if the token after the assumed operator is "TYPE" then skip

**Comment by flaiker** [comment]
That's a very pragmatic solution 👍

**Comment by larshp** [comment]
I'll implement the fix, give me 10 minutes 😄

**Comment by larshp** [comment]
There is quite a few workarounds like this in abapOpenChecks, this is the best we can do here, as we do not have an AST

**Comment by larshp** [comment]
PR opened, fix is not very nice but it works 🖍

**Comment by flaiker** [comment]
Thanks!
I just understood the error message by the way, I thought it was referring to `NEW #( )`

**Comment by larshp** [comment]
suggestions for better error descriptions welcome 😄

**Comment by flaiker** [comment]
Updated and the issue is now resolved.
