### ISSUE TITLE
Textelements for tranlsation

### ISSUE THREAD

**Issue by SeverX** [larshp/abapOpenChecks#678]
Hello Lars,

There is a problem that all classes (except ZCL_AOC_CHECK_70) contain no textelements for existing texts in IF_CI_TEST~QUERY_ATTRIBUTES, GET_MESSAGE_TEXT, CONSTRUCTOR. In this case it's not possible to translate texts in English into other languages using transaction SE61.

Could you probably create textelements for all texts in all check classes?

Kind regards
Sergej

**Comment by larshp** [comment]
feel free to open a PR with the changes of creating text elements for the texts

I'm typically lazy when it comes to developer tooling, I expect ABAP developers to be familiar with English as the ABAP language syntax is English

**Comment by ibnbr** [comment]
I think it's finished. I don't know how to check if there's more class without text elements.
