### ISSUE TITLE
oo constant check doesn't allow [:type:] placeholders

### ISSUE THREAD

**Issue by smb** [larshp/abapOpenChecks#679]
Code:
`CONSTANTS cv_block_type_none TYPE /namespace/de_lgpla_block_type VALUE ' '.`

Config:
`C[:type:]_`

Result:
`Bad naming, expected C[:type:]_, got CV_BLOCK_TYPE_NONE`

seems like [:type:] replacement is not applied to oo_oocons configuration

**Comment by larshp** [comment]
taking a look

**Comment by larshp** [comment]
try this, https://github.com/larshp/abapOpenChecks/pull/680

more identifiers are being resolved now, so it might cause some regressions. Already checking abapGit and abapOpenChecks itself gives errors
