### ISSUE TITLE
Refactoring: use scimessages instead of GET_MESSAGE_TEXT

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#698]
see discussion in https://github.com/larshp/abapOpenChecks/pull/692

okay with multiple PRs

**Comment by ibnbr** [comment]
I am developing something to automate this refactoring. I must create PR soon.

Trying to create text elements on this refactoring, and resolve issue #678  too.

**Comment by ibnbr** [comment]
Finished this, we no longer have any classes that redefine the method GET_MESSAGE_TEXT .
