### ISSUE TITLE
new check: string literals with LIKE, CP, NP

### ISSUE THREAD

**Issue by marcissimus** [larshp/abapOpenChecks#721]
Raise warning when using literals in pattern comparisons that are most likely not working as  intended:

`SELECT ... WHERE xyz LIKE 'PATTERN*'.`
instead of
`SELECT ... WHERE xyz LIKE 'PATTERN%'.`

or

`IF xyz CP 'PATTERN%'.`
instead of
`IF xyz CP 'PATTERN*'.`

Operators: LIKE, CP, NP
Check literals for: ?* or .%
In SQL watch for ESCAPE of characters.

**Comment by larshp** [comment]
thanks, good idea
