### ISSUE TITLE
Check 69: Naming convention should default to SAP styleguide

### ISSUE THREAD

**Issue by swixfort** [larshp/abapOpenChecks#726]
I find this check is really dependend on where you are.
It should default to the [stylguide by SAP](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#avoid-encodings-esp-hungarian-notation-and-prefixes).

**Comment by larshp** [comment]
it defaults to something close to the default setting in the SAP standard extended naming conventions check

there are pros and cons for all the checks, I choose to use some of them, and leave some for other special cases

suggest making your own default and upload download it with https://github.com/larshp/upDOWNci

**Comment by swixfort** [comment]
I see. I guess it's not a big issue to do so, as you mentioned. It just seemed logical to do so as the styleguide suggests.

BR
