### ISSUE TITLE
Activation Error in ZAOC_LINES_TREE in release < NW 7.4

### ISSUE THREAD

**Issue by os-neff** [larshp/abapOpenChecks#737]
When trying to activate ZAOC_LINES_TREE, an error message is raised. The error message states that the messag statement is missing a message-id. This is a bit misleading, since the actual issue is that MESSAGE is unable to resolve a string with varialbe:

![grafik](https://user-images.githubusercontent.com/52742777/61273447-d5cffc80-a7a9-11e9-878a-ca3a4b399e67.png)

**Comment by larshp** [comment]
yea, thanks 👍

**Comment by larshp** [comment]
try this: https://github.com/larshp/abapOpenChecks/pull/738

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/issues/286 and https://github.com/abaplint/abaplint/issues/450 will when implemented make sure this does not happen again

**Comment by os-neff** [comment]
Thanks! Tested and works fine now.
