### ISSUE TITLE
New Check: Only Static Methods in one Class

### ISSUE THREAD

**Issue by DennstedtB** [larshp/abapOpenChecks#758]
As mentioned in the SAP Styleguide, methods should be instance methods by default. I've seen a lot of pure static classes. 
To prevent this I'd like to have a check which has a look if a class only contains static methods. Also SAP says that there is [only one accepted exception for this](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#prefer-objects-to-static-classes). 

> One accepted exception to this rule are plain type utils classes. Their methods make it easier to interact with certain ABAP types. They are not only completely stateless, but so basic that they look like ABAP statements or built-in functions. The discriminating factor is that their consumers tie them into their code so tightly that they actually don't want to mock them in unit tests.
> 
My suggestion is, that an info or error will be shown ( which could be ignored by ATC-quality process - exemptions ) when a class only contains static methods ( and maybe also only static members )

**Comment by larshp** [comment]
pull requests welcome

like the other abapOpenChecks the user can set if it should be enabled or not, and the type of error/warning/info.
Personally, I think this is something that should be caught during code review, some classes by nature will always be static, eg. https://github.com/larshp/abapGit/blob/master/src/zcl_abapgit_factory.clas.abap,

**Comment by DennstedtB** [comment]
Sure, there are some cases where static classes make sense. But in my opinion these should be rare. 

I'll create a PR after I have access to a system again.

**Comment by larshp** [comment]
I'm all for adding options in abapOpenChecks, some projects/customers/partners will find different relevant in different cases/approaches

**Comment by larshp** [comment]
merged, closing
