### ISSUE TITLE
Check 59 - Logical expression structure - boolean parser error

### ISSUE THREAD

**Issue by KuJo-Ger** [larshp/abapOpenChecks#760]
Check 59 returns `abapOpenChecks boolean parser error ` if you use keyword **_CONDITION_** in an **_ASSERT_** statement.

Code example:
`ASSERT FIELDS <lv_field1> <lv_field2> CONDITION <lv_check_val> IS NOT INITIAL.`

Without the keyword **_CONDITION_**, no warning is thrown. However, **_FIELDS_** must then also be omitted.

**Comment by larshp** [comment]
will have to skip this example, abapOpenChecks cannot parse it reliably
