### ISSUE TITLE
CHECK_69: Enable all occurrences of [:type:]

### ISSUE THREAD

**Issue by MiLiCLN** [larshp/abapOpenChecks#766]
To enable multiple values for the prefixes, all places of [:type:] must be replaced (REPLACE ALL OCCURRENCES OF ... ) .

Example:
Prefixes for Data Reference: (**R**|**O**)

Affected methods:
- FIELD_SYMBOL
- DATA
- CHECK_CONSTANT
- CHECK_FIELD_SYMBOL
- CHECK_FM_PARAMETERS

**Comment by larshp** [comment]
"multiple values for the prefixes" ? can you help with an example of the problem?

**Comment by MiLiCLN** [comment]
For example, we have to allow the prefixes R and O for the data references in order not to object to old coding.
Valid values should then be, for example, the following:
lo_object
lr_object

With "REPLACE FIRST OCCURANCE OF..." of course only the 1st [:type:] is replaced, the following places remain in [:type:].

The change of ".... FIRST OCCURANCE OF ..." by "... ALL OCCURANCES OF ..." solves this problem.

![Multiple Prefixes](https://user-images.githubusercontent.com/49416412/64433823-829a6c00-d0bf-11e9-953f-850d512616d1.png)

**Comment by MiLiCLN** [comment]
PR welcome? :smirk:

**Comment by larshp** [comment]
👍 yea, sure
