### ISSUE TITLE
Broken link for check 15

### ISSUE THREAD

**Issue by jwigert** [larshp/abapOpenChecks#773]
The link in the documentation for check 15 (https://www.cupfighter.net/2011/03/abap-underverse) seems to be broken. I was not able to retrieve it through the waybackmachine either. I would suggest adding some brief summary of the information which was previously available through the link.

**Comment by larshp** [comment]
I dont remember what it contained, suggest deleting it, pull requests welcome

**Comment by jwigert** [comment]
Ok, I created PR #774.
