### ISSUE TITLE
if_satc_namespace_access not available in 740

### ISSUE THREAD

**Issue by BlackmanCC** [larshp/abapOpenChecks#789]
We are using abapOpenChecks with Basis Release 740. 

In the last change of ZCL_AOC_SUPER interface if_satc_namespace_access is referenced. This interface does not exist in 740 so the AOC checks dump.

Change was made with "Observe registered ATC namespaces" #765

**Comment by larshp** [comment]
thanks,
does database table `SATC_AC_NAMESPCS` exist?
does class `cl_satc_namespace_access` exist?

**Comment by creyj** [comment]
Yes both on SAP_BASIS	740	0018	SAPKB7401.

**Comment by BlackmanCC** [comment]
The table exists, but the class does not exist on SAPKB74012.

![image](https://user-images.githubusercontent.com/56150286/66984602-4c3b0e00-f0bb-11e9-9000-bacbb242a23c.png)

**Comment by MiLiCLN** [comment]
I tested it with 7.40 SP7. But I suspect that the objects came into the system with an OSS hint (Remote ATC).

Discard the current version and keep it pragmatic like the SAP standard in S/4 (in INFORM-Method)? 

`IF p_sub_obj_name CP 'L*UXX'.`

**Comment by larshp** [comment]
Suggest looking up directly in the table, and if the table does not exist in the system, revert to the old behavior

**Comment by BlackmanCC** [comment]
Reverting to the old behavior sounds good.

**Comment by larshp** [comment]
taking a look

**Comment by larshp** [comment]
@BlackmanCC try again, latest version

**Comment by BlackmanCC** [comment]
@larshp Looks good. Thanks a lot..
