### ISSUE TITLE
Texts broken? 48 + 40

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#891]
check 48 + 40

something like the following will not work, the message is added twice plus what happens to the pragma?

@ibnbr 

```abap
    ls_message-test = myname.
    ls_message-code = '001'.
    ls_message-kind = c_error.
    ls_message-pcom = '"#EC CI_DEFAULT_KEY'.
    INSERT ls_message INTO TABLE scimessages.

    enable_rfc( ).

    insert_scimessage(
        iv_code = '001'
        iv_text = 'DEFAULT KEY, add table key or EMPTY KEY'(m01) ).
```

**Comment by ibnbr** [comment]
weird, I really don't' know what happened. I'll create a PR to adjust this checks.

**Comment by ibnbr** [comment]
check 69 too.

**Comment by larshp** [comment]
69 fixed in https://github.com/larshp/abapOpenChecks/pull/888

**Comment by ibnbr** [comment]
OK, I create a new parameter to pass "PCOM" to method insert_scimessage.

So I adjusted check 69 too.
