### ISSUE TITLE
check_89: FUNCTION 'LXE_OBJ_DOKU_GET_XSTRING_RFC' does not exists

### ISSUE THREAD

**Issue by FrankBuchholz** [larshp/abapOpenChecks#896]
CLASS zcl_aoc_check_89 claims that FUNCTION 'LXE_OBJ_DOKU_GET_XSTRING_RFC' exists.
However, this is not the case in my system running on S4HANA ON PREMISE 1909. 

```
    "function module already exists in 7.02 -> should work on every satellite system
    CALL FUNCTION 'LXE_OBJ_DOKU_GET_XSTRING_RFC'
      DESTINATION lv_destination
```

Well, as a workaround I simply can deactivate this check.

**Comment by larshp** [comment]
thanks, its difficult to know what is excatly part of each system/release

probably need to do custom code to make sure

**Comment by MiLiCLN** [comment]
Under S/4HANA 1909 "only" the RFC wrapper "LXE_OBJ_DOKU_GET_XSTRING_RFC" is missing. The module that is called inside exists (LXE_OBJ_DOKU_GET_XSTRING).
