### ISSUE TITLE
CHECK_06 - Pretty printer for Function Modules

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapOpenChecks#897]
When I activate a Function Module after, execute Pretty Painter, code changes and all Function Module interface to uppercase:
Before:
![image](https://user-images.githubusercontent.com/56556686/71083528-85fbc400-2193-11ea-879b-f21b61bf457d.png)
After:
![image](https://user-images.githubusercontent.com/56556686/71083546-8e53ff00-2193-11ea-8036-7bb0d1837da1.png)

I don't know if this is a SAP requirement or if it is an Eclipse bug.

If this is right, maybe CHECK_06 shouldn't check Function Modules interface

**Comment by jrodriguez-rc** [comment]
Same with include generated
![image](https://user-images.githubusercontent.com/56556686/71156752-ded56600-2240-11ea-8c57-56b6224e8ced.png)

**Comment by jrodriguez-rc** [comment]
Same for several checks (naming conventions, empty branch, bad indentation...), them are raised for a generated change document function module:
![image](https://user-images.githubusercontent.com/56556686/71580366-9f403100-2b00-11ea-8a44-2588d54f43a0.png)

It would be some way to check if some object is automatically generated to skip them?

**Comment by jelliottp** [comment]
I was about to report this. Was #909 meant to fix it for FM signatures? We're still running into it now as well.

**Comment by ConjuringCoffee** [comment]
@jelliottp, was this issue successfully fixed by #1106? :)
