### ISSUE TITLE
CHECK_55: Chaining up-front declarations

### ISSUE THREAD

**Issue by gabrielbaca** [larshp/abapOpenChecks#915]
The check suggests you to chain consecutive declarations, which goes against SAP style guidelines.

https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#do-not-chain-up-front-declarations

**Comment by larshp** [comment]
yea, its optional which checks to enable in the variant

abapOpenChecks offers a set of possibilities

feel free to add a note in the documentation, https://github.com/larshp/abapOpenChecks/blob/master/docs/_checks/55.md
