### ISSUE TITLE
check_84, syntax error

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#920]
ref https://github.com/larshp/abapOpenChecks/pull/912

@jrodriguez-rc

![image](https://user-images.githubusercontent.com/5888506/74099147-db63aa00-4b20-11ea-90d8-c30950947a7b.png)

**Comment by jrodriguez-rc** [comment]
Oh, sorry about this, I don't know what I was thinking about defining a new type for range instead use `TYPE RANGE OF`, also, I don't know types `sign` and `option` data types wasn't exists in 702.
I made new PR #921, but I made changes directly in GitHub, I can't test it until tomorrow

**Comment by larshp** [comment]
I did try that, but it must be dictionary to work

**Comment by jrodriguez-rc** [comment]
I could check it now but in version 750. I remove defined type for `TYPE RANGE OF`

**Comment by abap-weasel** [comment]
While the issue was already resolved, I'd like to mention the downward compatible DDIC for ranges in case a similar issue comes up again. I checked this in ERP 6.0 (no EHP).

DTEL DDSIGN for SIGN field
DTEL DDOPTION for OPTION field
