### ISSUE TITLE
checks.md- Check 100 missing / incorrect

### ISSUE THREAD

**Issue by MiLiCLN** [larshp/abapOpenChecks#923]
In the generated document checks.md the link to the latest check 100 is incorrect.

![aoc_checks_md_broken_link_100](https://user-images.githubusercontent.com/49416412/74284479-1c77dc00-4d24-11ea-8d16-2d6dcc1634b3.png)

**Comment by larshp** [comment]
now the link is shown, fixed in https://github.com/larshp/abapOpenChecks/commit/5cd85de3ce0e1932351579c1b35b3aed0d0782e8

however would like check 100 to be last on the page, not sure how to fix this, hmm

**Comment by MiLiCLN** [comment]
Maybe it is possible to add a new metadata attribute "cSort" or similar. cSort will be assigned the corresponding number in the check documents.
Then sort the order with "Liquid - Filter Sort" in checks.md.

**Comment by larshp** [comment]
try it out, https://docs.abapgit.org/development/docs.html describes how to build and run the docs locally
