### ISSUE TITLE
Update of Simplification Database via ReportZAOC_UPLOAD_SIDB fails

### ISSUE THREAD

**Issue by os-neff** [larshp/abapOpenChecks#924]
When trying to upload the most recent version of the simplification DB CCMSIDB00P_11-80001018.ZIP, the import is failing due to an unknown file.  SAP does provide a singature file "SIGNATURE.SMF" with the zip file. This file should be ignored during the upload.

**Comment by larshp** [comment]
thanks, pull requests welcome
