### ISSUE TITLE
CHECK 02 and 07 fail to dump on ABAP 7.54

### ISSUE THREAD

**Issue by lellmailru** [larshp/abapOpenChecks#932]
Hello!
Thank you for the project!

We use it on ABAP 7.5 and there is no problem.

But on ABAP 7.54 Code Inspector fails to dump ASSERTION_FAILED in CL_CI_TEST_SCAN=>INFORM:
![image](https://user-images.githubusercontent.com/38398506/75624235-a7315580-5bc3-11ea-9aa6-3c83a601f0a0.png)

Such dump exists only if checked class has code that violates CHECK 02 or 07

In SAP Support we get the next info:
"the problem is that check ZCL_AOC_CHECK_02 pretends using checksums without creating them. I.e. this check is erroneous. You should remove it from your variants.

And if you would like to use this check, create an issue on github, so that the author of the check corrects it."

Could you help us?

Best Regard, 
Elena Starkova

**Comment by larshp** [comment]
ref https://github.com/larshp/abapOpenChecks/commit/23e47418f7bcaf9d6b6bb6d7fa33f4c1d8092574

**Comment by larshp** [comment]
hi,
in the debugger, what are the values of `P_CHECKSUM_1` and `L_CHECKSUM_1`? Also please post the screenshot with the context, its not possible to see where exactly the code is from.

if you do not use the checksums, the temporary workaround is commenting the line `set_uses_checksum( ).` in the constructor

on 751
![image](https://user-images.githubusercontent.com/5888506/75624513-1d7a8b80-5bb5-11ea-8887-a698e8fd877d.png)

**Comment by gregorwolf** [comment]
Hope that helps:

P_CHECKSUM_1	                                   	0
L_CHECKSUM_1	                                   	1625247822-

![Screenshot 2020-03-01 at 16 29 17](https://user-images.githubusercontent.com/2639535/75628496-cf2bb380-5bd9-11ea-96cd-d108bf065c31.png)

**Comment by SleepwalkingDreamer** [comment]
Hi!
P_CHEKSUM_1 = 0 
L_CHECKSUM_1 = 1738033297

Here is screenshot
![image](https://user-images.githubusercontent.com/61741219/75777570-42aefb80-5d67-11ea-9ec1-392c4bc51b83.png)

**Comment by MiLiCLN** [comment]
With ABAP < 7.54, the Assert statement does not yet exist (checked with 7.54 and 7.52).
`assert P_CHECKSUM_1 = L_CHECKSUM_1.`

If checksums are to be used, the interface super->inform in ZCL_AOC_SUPER must be adapted and the calculated checksum must be passed.
![zcl_aoc_super](https://user-images.githubusercontent.com/49416412/75790295-46dd1800-5d6b-11ea-810d-694c221be2ac.png)

**Comment by larshp** [comment]
I think there is some magic code inside INFORM somewhere, that calculates the checksum based on the position and other fields

**Comment by MiLiCLN** [comment]
That's correct. But only the local version is calculated. If checksums are used in SAP checks, then "USES_CHECKSUM" is always set to true in the constructor and a checksum is passed to INFORM. 
![inform_1](https://user-images.githubusercontent.com/49416412/75796074-71cb6a00-5d73-11ea-9b5d-12f61b986123.png)
![inform_2](https://user-images.githubusercontent.com/49416412/75796093-755ef100-5d73-11ea-8fda-b0bd3e2f1461.png)
![inform_3](https://user-images.githubusercontent.com/49416412/75796101-7728b480-5d73-11ea-8661-385cfec3a95b.png)

**Comment by SeverX** [comment]
Hello,

I got the same error on a huge Z development package in a S4 (SAP_ABA = 75E), but for a bit more extended list of checks:
CHECKs 02, 07, 08, 11, 18, 53

Cheers
Serge

**Comment by larshp** [comment]
I dont have any system to reproduce on...

**Comment by jrodriguez-rc** [comment]
I am checking the error in a 754 system (happens to me for checks 02, 03, 08, 18 and 21)

Doing some changes to generate checksum and pass to `inform` method I found comment:
![image](https://user-images.githubusercontent.com/56556686/83775775-9fcc8d00-a687-11ea-9851-69684715c794.png)

The older version I can check is a 731 and attribute `p_checksum_1` exists, so I can't test in a previous system the change.

I'll implement a dynamical call to the method with(out) `p_checksum_1`  depending on the version

**Comment by larshp** [comment]
yea, that sounds good 👍

**Comment by jrodriguez-rc** [comment]
Argh! Discarded!

Can't make dynamic call to a super method:
![image](https://user-images.githubusercontent.com/56556686/83788388-6a2ea080-a695-11ea-97a2-aadc00ea438d.png)
![image](https://user-images.githubusercontent.com/56556686/83789430-01e0be80-a697-11ea-95b0-aed287157303.png)

And setting super->inform in a variable also fails
![image](https://user-images.githubusercontent.com/56556686/83789401-f392a280-a696-11ea-9113-f49306246677.png)

**Comment by jrodriguez-rc** [comment]
I made the changes in `zcl_aoc_super`, but... only works for 752 to up (and maybe 751)
[zcl_aoc_super.zip](https://github.com/larshp/abapOpenChecks/files/4731719/zcl_aoc_super.zip)

I attach the changes I've made, in case anyone can think of how to make it compatible with previous versions.

According to the comment, the parameter `p_checksum_1` for method `inform` doesn't exist in 730, and method `get_stmt_checksum` doesn't exist in 750

**Comment by larshp** [comment]
try `call method ('SUPER')->('INFORM')`

**Comment by jrodriguez-rc** [comment]
Nope
![image](https://user-images.githubusercontent.com/56556686/83848619-6ee36b00-a70e-11ea-8d89-cbfe34ac9e24.png)

Will it be an option to create a branch for specific versions?

I made the change [here](https://github.com/jrodriguez-rc/abapOpenChecks/tree/assertion-on-checksum), the only pending point is calling to `super->inform` passing `p_checksum_1` in 730

**Comment by larshp** [comment]
hmm, 😞 

![image](https://user-images.githubusercontent.com/5888506/83856436-d94dd880-a719-11ea-81ff-e0215e937135.png)

**Comment by larshp** [comment]
guess its the only solution is to move the version requirement to v740sp02

**Comment by larshp** [comment]
@jrodriguez-rc will https://github.com/larshp/abapOpenChecks/pull/948 work ?
