### ISSUE TITLE
Check 69 - Determine exception type in importing attribute

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapOpenChecks#935]
abapGit method zif_abapgit_gui_error_handler->handle_error has an importing exception `ix_error TYPE REF TO zcx_abapgit_exception`
Check 69 determines that it is an object instead of exception
![image](https://user-images.githubusercontent.com/56556686/75890444-ac460d00-5e2e-11ea-9644-943fb7158992.png)

**Comment by larshp** [comment]
thanks, looks like a bug in abapOpenChecks
