### ISSUE TITLE
CHECK_45 - CONCATENATE RESPECTING BLANKS => concat_lines_of

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapOpenChecks#945]
Hi, I don't know if this is an issue o more a question.

I'm using this sentence:
`CONCATENATE LINES OF lt_content INTO DATA(lv_string) RESPECTING BLANKS.`

A check detects it and tells me to replace by `concat_lines_of`
![image](https://user-images.githubusercontent.com/56556686/82425732-3a717d00-9a87-11ea-8df7-78ddb5435883.png)

The problem is that I cannot found a `RESPECTING BLANKS` addition for `concat_lines_of`

**Comment by larshp** [comment]
its a bug
