### ISSUE TITLE
empty IFs, refactoring

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#968]
`abapOpenChecks/src/parsing/zcl_aoc_structure.clas.locals_imp.abap`: Empty block, add code: If, 173
`abapOpenChecks/src/sidb/zcl_aoc_upload_sidb.clas.abap`: Empty block, add code: If, 106
`abapOpenChecks/src/sidb/zcl_aoc_upload_sidb.clas.abap`: Empty block, add code: ElseIf, 108
`abapOpenChecks/src/sidb/zcl_aoc_upload_sidb.clas.abap`: Empty block, add code: ElseIf, 112
`abapOpenChecks/src/sidb/zcl_aoc_upload_sidb.clas.abap`: Empty block, add code: ElseIf, 114
`abapOpenChecks/src/sidb/zcl_aoc_upload_sidb.clas.abap`: Empty block, add code: ElseIf, 116
`abapOpenChecks/src/sidb/zcl_aoc_upload_sidb.clas.abap`: Empty block, add code: ElseIf, 120
`abapOpenChecks/src/sidb/zcl_aoc_upload_sidb.clas.abap`: Empty block, add code: ElseIf, 122
`abapOpenChecks/src/sidb/zcl_aoc_upload_sidb.clas.abap`: Empty block, add code: ElseIf, 124
`abapOpenChecks/src/sidb/zcl_aoc_upload_sidb.clas.abap`: Empty block, add code: ElseIf, 130

**Comment by g-back** [comment]
think this was closed with #969?
