### ISSUE TITLE
Dump in CL_CI_TEST_SCAN->INFORM, when GET_STMT_CHECKSUM is called with 'P_VERSION = 2'

### ISSUE THREAD

**Issue by mkaesemann** [larshp/abapOpenChecks#979]
The fix in #955 causes dumps in an S/4HANA 1709 and 1809 system, because GET_STMT_CHECKSUM does have a P_VERSION parameter, but the underlying GET_STMT_CHECKSUM_DO method does not know the value P_VERSION = 2 and thus does not return a checksum.
This, in turn, causes a dump in method INFORM of CL_CI_TEST_SCAN, when the assert in line 206 fails:

```ABAP
    if USES_CHECKSUM = ABAP_TRUE.
      if P_CHECKSUM_1 is initial.
        if P_POSITION is supplied and P_POSITION is not initial.
          data L_CHECKSUM type SCI_CRC64.
          clear L_CHECKSUM.
          GET_STMT_CHECKSUM( exporting P_POSITION = P_POSITION changing P_CHECKSUM = L_CHECKSUM exceptions ERROR = 0 ).
          L_CHECKSUM_1 = L_CHECKSUM-I1.
        else.
          clear L_CHECKSUM_1.
        endif.
      else.
        L_CHECKSUM_1 = P_CHECKSUM_1.
      endif.
    else.
      clear L_CHECKSUM_1.
    endif.
*   just to be sure that nothing has been destroyed
    if P_TEST <> 'CL_CI_TEST_SHO_CLIENT' and P_TEST <> 'CL_CI_TEST_COMPLEX_WHERE'
    and P_TEST <> 'CL_CI_TEST_SELECT_TAW_SEC01' and P_TEST <> 'CL_CI_TEST_SPEC_CRIT_STMNTS'.
      assert P_CHECKSUM_1 = L_CHECKSUM_1.       ""<<<<<<<<<<<<<<<< THIS ASSERT FAILS!
    endif.

    raise event MESSAGE
      exporting
        P_SUB_OBJ_TYPE = P_SUB_OBJ_TYPE
        P_SUB_OBJ_NAME = P_SUB_OBJ_NAME
        P_LINE         = P_LINE
        P_COLUMN       = P_COLUMN
        P_ERRCNT       = P_ERRCNT
        P_KIND         = L_KIND
        P_TEST         = P_TEST
        P_CODE         = P_CODE
        P_SUPPRESS     = L_SUPPRESS
        P_PARAM_1      = P_PARAM_1
        P_PARAM_2      = P_PARAM_2
        P_PARAM_3      = P_PARAM_3
        P_PARAM_4      = P_PARAM_4
        P_CHECKSUM_1   = L_CHECKSUM_1
        P_INCLSPEC     = P_INCLSPEC
        P_DETAIL       = P_DETAIL.
```

What exactly is the reasoning behind P_VERSION = 2 and in what version does this work?

_Originally posted by @mkaesemann in https://github.com/larshp/abapOpenChecks/pull/955#issuecomment-720552428_

**Comment by mkaesemann** [comment]
Just tested it with the default value of P_VERSION = 1 and that one works fine.

**Comment by larshp** [comment]
what is the actual dump, is it something that can be caught?

**Comment by larshp** [comment]
the code is basically dark magic, its not easy to tell what happens on the different versions, and everyone only have access to few versions

**Comment by mkaesemann** [comment]
The dump is caused by the assert statement, so it can't be caught.
At first glance, the p_version parameter has a default value, so I'm unclear on why we need to supply a version in the first place. If you can give me a hint as to what version that comes from I can check in our landscape if we have a system I can compare against.

**Comment by larshp** [comment]
@jrodriguez-rc can you help? I'm not sure when this was first introduced, but its mentioned in https://github.com/larshp/abapOpenChecks/pull/952

**Comment by jrodriguez-rc** [comment]
What is the code and check that raise the exception? It should be testable in NPL server (I think S/4HANA 1709 is BASIS 752)

I can test it in a customer system with 1909. I don't get any error in this system.

**Comment by jrodriguez-rc** [comment]
@mkaesemann try calling to method `enable_checksum` in the `constructor` of the check class.

The checksum error for S/4 was treated in PR #950

**Comment by mkaesemann** [comment]
@jrodriguez-rc
I think there is a misunderstanding. The issue is not that the checksum is not used. The issue is that the checksum is used, but never calculated, because the provided value for ``P_VERSION`` is invalid - there is no version '2' in ``GET_STMT_CHECKSUM``.
And since the code in ``INFORM`` of ``CL_CI_TEST_SCAN`` calls ``GET_STMT_CHECKSUM`` without a ``P_VERSION`` value (as shown in the code snippet I pasted) to compare the checksum against, this will always lead to dump when the assert statement is reached.
So, the question was, where ``P_VERSION = 2`` comes from for the ``GET_STMT_CHECKSUM`` call in ``ZCL_AOC_SUPER=>GET_CHECKSUM``.

I did some research in our systems and was able to identify the following:

- System prior to and including 750 do not have ``CL_CI_TEST_SCAN-> GET_STMT_CHECKSUM`` at all.
- In 751 ``CL_CI_TEST_SCAN-> GET_STMT_CHECKSUM`` exists but has no ``P_VERSION`` parameter.
- Starting with 752 ``CL_CI_TEST_SCAN-> GET_STMT_CHECKSUM`` exists, has a ``P_VERSION`` parameter with default value '1' and does not know a ``P_VERSION = 2`` case.
- In 754 and 755, method ``GET_STMT_CHECKSUM_DO`` does indeed support ``P_VERSION = 2``, but the default is still 1. In these versions ``INFORM`` also calls ``GET_STMT_CHECKSUM`` with ``P_VERSION = 2`` if checksums are used, unfortunately.

So, the answer to my question is probably, that you were using a 754 or 755 system when implementing #955 and the current state only covers systems older than 752 or newer than 753, but not 752 and 753 if checksums are used.

Which would then lead to the questions why do the checks need checksums in the first place? 
If checksums are indeed required, we'll probably have to check the basis version to decide what the correct handling for its calculation needs to be.

**Comment by larshp** [comment]
looking at other calls of GET_STMT_CHECKSUM in the standard system, the P_VERSION is not supplied, at least on 752

so suggest trying to leave it out, I'll open a PR

**Comment by jrodriguez-rc** [comment]
I'm testing the change with a package, if there are no errors, the change would be OK

**Comment by jrodriguez-rc** [comment]
Done, no dumps raised :)

**Comment by mkaesemann** [comment]
Did you test it in a 754+ system? 
I haven't verified if version 2 and version 1 return the same checksum. If they don't then there will be failed asserts if one checksum calculation is done version 1 and the one in ``INFORM`` is calculated with version 2 and compared to the version 1 one.

**Comment by jrodriguez-rc** [comment]
I tested it in a 754 system (S/4HANA 1909)
