### ISSUE TITLE
Add check number to the class description

### ISSUE THREAD

**Issue by MiLiCLN** [larshp/abapOpenChecks#982]
It happens quite often that I want to review the check settings in the transaction SCI. Most of the time I know the check number of the single check but I have to search and scroll in the small overview for a long time until I find the right check. With the number in the class description this would be a great help to get to the right check faster.

**Comment by larshp** [comment]
thats a good idea, I have the same problem

**Comment by g-back** [comment]
I'll go ahead with checks 1-20, @larshp how do you want the formatting to be exactly?

001 - IF in iF
001: IF in IF
CHECK_001: IF in IF
...

**Comment by larshp** [comment]
probably "001 - IF in iF", then it looks a bit like https://docs.abapopenchecks.org/checks/
